### ISSUE TITLE
ModulesLoader cannot handle .DS_Store

### ISSUE THREAD

**Issue by mariannemyers** [rjrudin/ml-javaclient-util#10]
I'm regularly getting this error now.  Can we add logic to ignore .DS_Store?  'gradle test' breaks now in certain situations on my MBP with OS X Yosemite because there are invalid chars in files that reside under .DS_Store.
```
java.lang.RuntimeException: Unable to insert content at URI: /ext/.DS_Store; cause: Authorization failed for user 'obi-tester'.
	at com.rjrudin.marklogic.modulesloader.impl.XccAssetLoader.loadFile(XccAssetLoader.java:153)
	at com.rjrudin.marklogic.modulesloader.impl.XccAssetLoader.visitFile(XccAssetLoader.java:114)
	at com.rjrudin.marklogic.modulesloader.impl.XccAssetLoader.visitFile(XccAssetLoader.java:35)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:135)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
	at java.nio.file.Files.walkFileTree(Files.java:2602)
	at java.nio.file.Files.walkFileTree(Files.java:2635)
...
```

**Comment by rjrudin** [comment]
Fixed in 2.2.2 - XccAssetLoader now has a FileFilter attribute that defaults to ignoring directories that start with ".".
